# Jekyll configuration

name: Kurdish-BLARK
description: Kurdish Basic Language Resource Kit (BLARK)

# url is currently only used only for the RSS feed in feed.xml
url: ''

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# These can be '' to hide the Github or Gitlab nav buttons
github: 'KurdishBLARK'
gitlab: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: false

# Set this to your public isso URL to enable comments via isso. Set to '' to disable isso.
isso: ''

# Set this to your disqus shortname to enable comments via disqus. Set to '' to disable disqus.
disqus: ''

permalink: /:categories/:title.html
paginate: 3

highlighter: rouge
markdown: kramdown
plugins: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']

theme: jekyll-theme-slate